# Column 1: 5' replaced 
# Coulmn 2: 5' inserted
# Coulmn 3: 3' inserted
# Column 4: 3' replaced 

'us/0/0'     = ['----', '--------------', '--------------', '----']
'us/0/1'     = ['U---', '--------------', '--------------', '---U']
'us/0/2'     = ['UU--', '--------------', '--------------', '--UU']
'us/0/3'     = ['UUU-', '--------------', '--------------', '-UUU']
'us/1/0'     = ['G---', '--------------', '--------------', '---C']
'us/1/1'     = ['GU--', '--------------', '--------------', '--UC']
'us/1/2'     = ['GUU-', '--------------', '--------------', '-UUC']
'us/1/3'     = ['GUUU', '--------------', '--------------', 'UUUC']
'us/2/2'     = ['GCUU', '--------------', '--------------', 'UUGC']
'us/2/6'     = ['GCUU', 'UCCC----------', '----------UUUC', 'CCGC']
'us/2/10'    = ['GCUU', 'UCCCUUUC------', '------UUUCCCUU', 'UCGC']
'us/2/14'    = ['GCUU', 'UCCCUUUCCCUU--', '--UUUCCCUUUCCC', 'UUGC']
'us/4/2'     = ['GCUA', 'UU------------', '------------UU', 'UAGC']
'us/4/6'     = ['GCUA', 'UUUCCC--------', '--------UUUCCC', 'UAGC']
'us/4/10'    = ['GCUA', 'UUUCCCUUUC----', '----UUUCCCUUUC', 'UAGC']
'us/4/14'    = ['GCUA', 'UUUCCCUUUCCCUU', 'UUUCCCUUUCCCUU', 'UAGC']
'ls/5'       = ['-------', '--------------', '--------------', '---------']
'ls/6'       = ['------', '--------------', '--------------', '--------']
'ls/6/2'     = ['UU----', '--------------', '--------------', '------UU']
'ls/6/4'     = ['UUUC--', '--------------', '--------------', '----UUUC']
'ls/6/6'     = ['UUUCCC', '--------------', '--------------', '--UUUCCC']
'cb'         = ['ACUU--', '--------------', '--------------', 'AAGU']
'cb/wo'      = ['ACUU--', '--------------', '--------------', 'AGGU']
'cb/mo'      = ['ACUU--', '--------------', '--------------', 'ACGU']
'cb/bo'      = ['ACUU--', '--------------', '-------------A', 'AAGU']
'cb/wo2'     = ['ACUU--', '--------------', '--------------', 'GGGU']
'cl'         = ['AGCCUUGA----', '--------------', '--------------', '----AAGUAAGGCU']
'cl/wo'      = ['AGCCUUGA----', '--------------', '--------------', '----AAGUAGGGCU']
'cl/mo'      = ['AGCCUUGA----', '--------------', '--------------', '----AAGUAACGCU']
'cl/bo'      = ['AGCCUUGA----', '--------------', '--------------', '---AAGUAAGAGCU']
'sb/2'       = ['UCGU', '--------------', '--------------', 'ACGA']
'sb/5'       = ['UCGU', 'UAA-----------', '-----------UUA', 'ACGA']
'sb/8'       = ['UCGU', 'UAAAAU--------', '--------AUUUUA', 'ACGA']
'sb/2/bo'    = ['UCGA', 'U-------------', '--------------', 'ACGA']
'sb/3'       = ['UCGU', 'U-------------', '-------------A', 'ACGA']
'sb/3/mo'    = ['UCGC', 'U-------------', '-------------A', 'ACGA']
'sb/3/bo'    = ['UCGA', 'UU------------', '-------------A', 'ACGA']
'sb/4'       = ['UCGU', 'UA------------', '------------UA', 'ACGA']
'sb/4/wo'    = ['UCGU', 'UG------------', '------------UA', 'ACGA']
'sb/4/mo'    = ['UCGC', 'UA------------', '------------UA', 'ACGA']
'sb/4/bo'    = ['UCGU', 'AUA-----------', '------------UA', 'ACGA']
'sb/5/mo'    = ['UCGC', 'UAA-----------', '-----------UUA', 'ACGA']
'sb/6'       = ['UCGU', 'UAAA----------', '----------UUUA', 'ACGA']
'sb/6/mo'    = ['UCGC', 'UAAA----------', '----------UUUA', 'ACGA']
'sb/6/wo'    = ['UCGU', 'UGAA----------', '----------UUUA', 'ACGA']
'sl'         = ['UCGGCUGA----', '--------------', '--------------', '----AAGUAGCCGA']
'slx'        = ['GUUAUCGA----', '--------------', '--------------', '----AAGUGAUAAC']
'slx/wo'     = ['GUUGUCGA----', '--------------', '--------------', '----AAGUGAUAAC']
'slx/mx'     = ['GGUAUCGA----', '--------------', '--------------', '----AAGUGAUACC']
'slx/mo'     = ['GCUAUCGA----', '--------------', '--------------', '----AAGUGAUAAC']
'slx/bo'     = ['GUUAAUCGA---', '--------------', '--------------', '----AAGUGAUAAC']
'id/0'       = ['GA----', '--------------', '--------------', '----']
'id/1'       = ['GAG---', '--------------', '--------------', '---C']
'id/2'       = ['GAGC--', '--------------', '--------------', '--GC']
'id/3'       = ['GAGCU-', '--------------', '--------------', '-AGC']
'id/4'       = ['GAGCUA', '--------------', '--------------', 'UAGC']

'nx/0'       = ['GG', '---', '---', 'CC']
'nx/1'       = ['GG', 'U--', '--U', 'CC']
'nx/2'       = ['GG', 'UU-', '-UU', 'CC']
'nx/3'       = ['GG', 'UUU', 'UUU', 'CC']
'nxx/0/0'    = ['--', '---', '---', '--']
'nxx/1/1'    = ['G-', '---', '---', '-C']
'nxx/2/3'    = ['GG', '---', '--U', 'CC']
'nxx/3/4'    = ['GG', 'C--', '-GU', 'CC']

'hp/17'      = ['----------------', '', '', '']
'hp/18'      = ['---------------', '', '', '']
'hp/33'      = ['', '', '', '']
'fh/1/0'     = ['----', '', '', '----']
'fh/2/0'     = ['---------------', '', '', '']  # Same as hp/18
'ch/4'       = ['AUCA', '---', '---', 'UGAU',]
'ch/5'       = ['UAUC', 'A--', '--U', 'GAUA',]
'ch/5/wo'    = ['UGUC', 'A--', '--U', 'GAUA',]
'ch/6'       = ['UUAU', 'CA-', '-UG', 'AUAA',]
'ch/6/wo'    = ['UUGU', 'CA-', '-UG', 'AUAA',]
'sh/5'       = ['AACG', 'G--', '--C', 'CGUU',]
'sh/7'       = ['AACG', 'GAC', 'GUC', 'CGUU',]
'sh/4'       = ['AACG', '---', '---', 'CGUU',]
'sh/4/mx'    = ['AAAG', '---', '---', 'CUUU',]
'sh/4/bx'    = ['AAAC', 'G--', '--C', 'GUUU',]
'sh/5/mx'    = ['AAAG', 'G--', '--C', 'CUUU',]
'sh/5/bxg'   = ['AAGC', 'GG-', '-CC', 'GCUU',]
'sh/6'       = ['AACG', 'GA-', '-UC', 'CGUU',]
'sh/7/wx'    = ['AAUG', 'GAC', 'GUC', 'CAUU',]
'sh/4/wx'    = ['AAUG', '---', '---', 'CAUU',]
'sh/5/wx'    = ['AAUG', 'G--', '--C', 'CAUU',]
