#!/bin/bash
set -eo pipefail
#$ -S /bin/bash
#$ -o stdout
#$ -j y
#$ -cwd
#$ -l mem_free=200M
#$ -l arch=linux-x64
#$ -l netapp=1G,scratch=1G
#$ -l h_rt=36:00:00

# Make sure the expected environment variables are defined.
if [ "x$SGE_TASK_ID" = x ] || \
   [ "x$ADDAPT_ARGS" = x ] || \
   [ "x$OUTPUT_PREFIX" = x ]; then
    echo "Usage:"
    echo "SGE_TASK_ID=<id> ADDAPT_ARGS=<...> OUTPUT_PREFIX=<name> ./sgrna_mc"
    echo
    env
    exit 1
fi

# Specify where the output files will be created.
output_dir=$(dirname $OUTPUT_PREFIX)
commit_path=$(printf "./${OUTPUT_PREFIX}_%03d.commit" "$SGE_TASK_ID")
tmp_traj_path=$(mktemp "/scratch/sgrna_mc.XXXXXXXX")
traj_path=$(printf "./${OUTPUT_PREFIX}_%03d.tsv" "$SGE_TASK_ID")

# Clean up files from previous runs.
mkdir -p $output_dir
rm -f $commit_path $traj_path

# Make sure everything has been committed.
. scripts/require_commit.sh > $commit_path

# Make sure the output file is copied from scratch when the program ends.
trap "mv $tmp_traj_path $traj_path" EXIT

# Run the design simulation.
echo "addapt version $(addapt --version)"
eval addapt \
    $ADDAPT_ARGS \
    -r $SGE_TASK_ID \
    -o $tmp_traj_path

# Report how much resource the simulation used.
qstat -j $JOB_ID
