expt = 'plate_reader/20180720_b_subtilis_theo_growth_curve.xlsx'
format = 'PerkinElmer'

t_lim = [30, 240]
gfp_lim = [15000, 40000]
od_lim = [0.05, 0.15]
fit_max_t = 0
fit_max_od = 0.08

[layout.on]
'1000 µM' = ['B03', 'C03', 'D03']
 '500 µM' = ['B04', 'C04', 'D04']
 '250 µM' = ['B05', 'C05', 'D05']
 '125 µM' = ['B06', 'C06', 'D06']
  '62 µM' = ['B07', 'C07', 'D07']
  '31 µM' = ['B08', 'C08', 'D08']
   '0 µM' = ['B09', 'C09', 'D09']

[layout.off]
'1000 µM' = ['E03', 'F03', 'G03']
 '500 µM' = ['E04', 'F04', 'G04']
 '250 µM' = ['E05', 'F05', 'G05']
 '125 µM' = ['E06', 'F06', 'G06']
  '62 µM' = ['E07', 'F07', 'G07']
  '31 µM' = ['E08', 'F08', 'G08']
   '0 µM' = ['E09', 'F09', 'G09']
